"""
SQLAlchemy models for the Pharmacy Agent system.
Defines all database tables and relationships.
"""
from sqlalchemy import Column, Integer, String, Float, Boolean, DateTime, ForeignKey, Text
from sqlalchemy.orm import relationship
from datetime import datetime
from .database import Base


class Medicine(Base):
    """
    Medicine Master Data - Source of truth for all medicines.
    Contains stock levels, pricing, and prescription requirements.
    """
    __tablename__ = "medicines"
    
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(200), nullable=False, index=True)
    stock_level = Column(Integer, default=0)
    unit_type = Column(String(50), default="tablets")  # tablets, capsules, ml, etc.
    prescription_required = Column(Boolean, default=False)
    price = Column(Float, default=0.0)
    dosage_info = Column(String(500), nullable=True)
    category = Column(String(100), default="General", index=True)  # Pain Relief, Diabetes, etc.
    safety_notes = Column(Text, nullable=True)  # Safety warnings and drug interactions
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    orders = relationship("Order", back_populates="medicine")
    order_history = relationship("OrderHistory", back_populates="medicine")


class Customer(Base):
    """
    Customer information including verification status.
    """
    __tablename__ = "customers"
    
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(200), nullable=False)
    email = Column(String(200), nullable=True, index=True)
    phone = Column(String(50), nullable=True)
    has_verified_prescription = Column(Boolean, default=False)
    prescription_file_path = Column(String(500), nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    orders = relationship("Order", back_populates="customer")
    order_history = relationship("OrderHistory", back_populates="customer")
    alerts = relationship("ProactiveAlert", back_populates="customer")


class Order(Base):
    """
    Active orders in the system.
    Tracks order lifecycle from creation to fulfillment.
    """
    __tablename__ = "orders"
    
    id = Column(Integer, primary_key=True, index=True)
    customer_id = Column(Integer, ForeignKey("customers.id"), nullable=False)
    medicine_id = Column(Integer, ForeignKey("medicines.id"), nullable=False)
    quantity = Column(Integer, nullable=False)
    total_price = Column(Float, default=0.0)
    status = Column(String(50), default="pending")  # pending, approved, rejected, fulfilled
    rejection_reason = Column(String(500), nullable=True)
    prescription_verified = Column(Boolean, default=False)
    webhook_triggered = Column(Boolean, default=False)
    notification_sent = Column(Boolean, default=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    customer = relationship("Customer", back_populates="orders")
    medicine = relationship("Medicine", back_populates="orders")


class OrderHistory(Base):
    """
    Historical order data for refill prediction.
    Used by the Refill Prediction Agent.
    """
    __tablename__ = "order_history"
    
    id = Column(Integer, primary_key=True, index=True)
    customer_id = Column(Integer, ForeignKey("customers.id"), nullable=False)
    customer_name = Column(String(200), nullable=True)
    customer_email = Column(String(200), nullable=True)
    medicine_id = Column(Integer, ForeignKey("medicines.id"), nullable=False)
    medicine_name = Column(String(200), nullable=True)
    quantity = Column(Integer, nullable=False)
    frequency_days = Column(Integer, default=1)  # How often taken (1 = daily, 0 = as needed)
    purchase_date = Column(DateTime, nullable=False)
    status = Column(String(50), default="completed")
    
    # Relationships
    customer = relationship("Customer", back_populates="order_history")
    medicine = relationship("Medicine", back_populates="order_history")


class ProactiveAlert(Base):
    """
    Proactive refill alerts generated by the Refill Prediction Agent.
    """
    __tablename__ = "proactive_alerts"
    
    id = Column(Integer, primary_key=True, index=True)
    customer_id = Column(Integer, ForeignKey("customers.id"), nullable=False)
    medicine_id = Column(Integer, ForeignKey("medicines.id"), nullable=False)
    medicine_name = Column(String(200), nullable=True)
    expected_refill_date = Column(DateTime, nullable=False)
    alert_message = Column(Text, nullable=True)
    status = Column(String(50), default="pending")  # pending, sent, acknowledged, dismissed
    created_at = Column(DateTime, default=datetime.utcnow)
    sent_at = Column(DateTime, nullable=True)
    
    # Relationships
    customer = relationship("Customer", back_populates="alerts")


class ConversationMemory(Base):
    """
    Stores conversation context per user for the Conversation Agent.
    """
    __tablename__ = "conversation_memory"
    
    id = Column(Integer, primary_key=True, index=True)
    session_id = Column(String(100), nullable=False, index=True)
    customer_id = Column(Integer, nullable=True)
    messages = Column(Text, nullable=True)  # JSON array of messages
    context = Column(Text, nullable=True)  # JSON object for extracted entities
    last_activity = Column(DateTime, default=datetime.utcnow)
    created_at = Column(DateTime, default=datetime.utcnow)


class AgentTrace(Base):
    """
    Stores agent interaction traces for observability.
    """
    __tablename__ = "agent_traces"
    
    id = Column(Integer, primary_key=True, index=True)
    trace_id = Column(String(100), nullable=False, index=True)
    session_id = Column(String(100), nullable=True)
    agent_name = Column(String(100), nullable=False)
    action = Column(String(100), nullable=False)
    input_data = Column(Text, nullable=True)  # JSON
    output_data = Column(Text, nullable=True)  # JSON
    decision = Column(String(200), nullable=True)
    reason = Column(Text, nullable=True)
    duration_ms = Column(Integer, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)


class UserSettings(Base):
    """
    User settings for preferences, notifications, and system options.
    Persists user preferences for the Settings page.
    """
    __tablename__ = "user_settings"
    
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, unique=True, nullable=False, index=True)
    language = Column(String(10), default="en")
    dark_mode = Column(Boolean, default=True)
    push_notifications = Column(Boolean, default=True)
    email_alerts = Column(Boolean, default=True)
    sms_alerts = Column(Boolean, default=False)
    auto_refill = Column(Boolean, default=True)
    voice_assistant = Column(Boolean, default=True)
    data_sharing = Column(Boolean, default=False)
    admin_mode = Column(Boolean, default=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


class Cart(Base):
    """
    Shopping cart for users.
    Each user can have one active cart.
    """
    __tablename__ = "carts"
    
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, nullable=False, index=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    items = relationship("CartItem", back_populates="cart", cascade="all, delete-orphan")


class CartItem(Base):
    """
    Individual items in a shopping cart.
    """
    __tablename__ = "cart_items"
    
    id = Column(Integer, primary_key=True, index=True)
    cart_id = Column(Integer, ForeignKey("carts.id"), nullable=False)
    medicine_id = Column(Integer, ForeignKey("medicines.id"), nullable=False)
    quantity = Column(Integer, default=1)
    added_at = Column(DateTime, default=datetime.utcnow)
    
    # Relationships
    cart = relationship("Cart", back_populates="items")
    medicine = relationship("Medicine")


class StockNotification(Base):
    """
    Stock level notifications for admin alerts.
    Triggered when medicine stock falls below threshold.
    """
    __tablename__ = "stock_notifications"
    
    id = Column(Integer, primary_key=True, index=True)
    medicine_id = Column(Integer, ForeignKey("medicines.id"), nullable=False)
    medicine_name = Column(String(200), nullable=False)
    stock_level = Column(Integer, nullable=False)
    threshold = Column(Integer, default=20)
    notification_type = Column(String(50), default="low_stock")  # low_stock, out_of_stock
    is_read = Column(Boolean, default=False)
    is_acknowledged = Column(Boolean, default=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    
    # Relationships
    medicine = relationship("Medicine")
