"""
Alerts API routes.
Handles proactive refill alerts generated by the Refill Prediction Agent.
"""
from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.orm import Session
from typing import List, Optional
from pydantic import BaseModel
from datetime import datetime

from ..database import get_db
from ..models import ProactiveAlert, Customer, Medicine

router = APIRouter(prefix="/alerts", tags=["Alerts"])


# Pydantic schemas
class AlertCreate(BaseModel):
    customer_id: int
    medicine_id: int
    medicine_name: Optional[str] = None
    expected_refill_date: datetime
    alert_message: Optional[str] = None


class AlertResponse(BaseModel):
    id: int
    customer_id: int
    customer_name: Optional[str] = None
    customer_email: Optional[str] = None
    medicine_id: int
    medicine_name: Optional[str] = None
    expected_refill_date: datetime
    alert_message: Optional[str] = None
    status: str
    created_at: datetime
    sent_at: Optional[datetime] = None
    
    class Config:
        from_attributes = True


class AlertStatusUpdate(BaseModel):
    status: str  # pending, sent, acknowledged, dismissed


# Endpoints
@router.get("", response_model=List[AlertResponse])
def get_alerts(
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=500),
    status: Optional[str] = None,
    customer_id: Optional[int] = None,
    db: Session = Depends(get_db)
):
    """Get all proactive refill alerts."""
    query = db.query(ProactiveAlert)
    
    if status:
        query = query.filter(ProactiveAlert.status == status)
    
    if customer_id:
        query = query.filter(ProactiveAlert.customer_id == customer_id)
    
    alerts = query.order_by(ProactiveAlert.expected_refill_date).offset(skip).limit(limit).all()
    
    # Enrich with customer details
    result = []
    for alert in alerts:
        customer = db.query(Customer).filter(Customer.id == alert.customer_id).first()
        result.append({
            "id": alert.id,
            "customer_id": alert.customer_id,
            "customer_name": customer.name if customer else None,
            "customer_email": customer.email if customer else None,
            "medicine_id": alert.medicine_id,
            "medicine_name": alert.medicine_name,
            "expected_refill_date": alert.expected_refill_date,
            "alert_message": alert.alert_message,
            "status": alert.status,
            "created_at": alert.created_at,
            "sent_at": alert.sent_at
        })
    
    return result


@router.get("/pending", response_model=List[AlertResponse])
def get_pending_alerts(db: Session = Depends(get_db)):
    """Get all pending refill alerts that need to be sent."""
    alerts = db.query(ProactiveAlert).filter(
        ProactiveAlert.status == "pending"
    ).order_by(ProactiveAlert.expected_refill_date).all()
    
    result = []
    for alert in alerts:
        customer = db.query(Customer).filter(Customer.id == alert.customer_id).first()
        result.append({
            "id": alert.id,
            "customer_id": alert.customer_id,
            "customer_name": customer.name if customer else None,
            "customer_email": customer.email if customer else None,
            "medicine_id": alert.medicine_id,
            "medicine_name": alert.medicine_name,
            "expected_refill_date": alert.expected_refill_date,
            "alert_message": alert.alert_message,
            "status": alert.status,
            "created_at": alert.created_at,
            "sent_at": alert.sent_at
        })
    
    return result


@router.post("", response_model=AlertResponse)
def create_alert(alert: AlertCreate, db: Session = Depends(get_db)):
    """Create a new proactive refill alert."""
    # Verify customer exists
    customer = db.query(Customer).filter(Customer.id == alert.customer_id).first()
    if not customer:
        raise HTTPException(status_code=404, detail="Customer not found")
    
    # Verify medicine exists
    medicine = db.query(Medicine).filter(Medicine.id == alert.medicine_id).first()
    if not medicine:
        raise HTTPException(status_code=404, detail="Medicine not found")
    
    # Create alert
    db_alert = ProactiveAlert(
        customer_id=alert.customer_id,
        medicine_id=alert.medicine_id,
        medicine_name=alert.medicine_name or medicine.name,
        expected_refill_date=alert.expected_refill_date,
        alert_message=alert.alert_message
    )
    
    db.add(db_alert)
    db.commit()
    db.refresh(db_alert)
    
    return {
        "id": db_alert.id,
        "customer_id": db_alert.customer_id,
        "customer_name": customer.name,
        "customer_email": customer.email,
        "medicine_id": db_alert.medicine_id,
        "medicine_name": db_alert.medicine_name,
        "expected_refill_date": db_alert.expected_refill_date,
        "alert_message": db_alert.alert_message,
        "status": db_alert.status,
        "created_at": db_alert.created_at,
        "sent_at": db_alert.sent_at
    }


@router.patch("/{alert_id}/status")
def update_alert_status(
    alert_id: int,
    update: AlertStatusUpdate,
    db: Session = Depends(get_db)
):
    """Update alert status."""
    alert = db.query(ProactiveAlert).filter(ProactiveAlert.id == alert_id).first()
    if not alert:
        raise HTTPException(status_code=404, detail="Alert not found")
    
    valid_statuses = ["pending", "sent", "acknowledged", "dismissed"]
    if update.status not in valid_statuses:
        raise HTTPException(
            status_code=400, 
            detail=f"Invalid status. Must be one of: {valid_statuses}"
        )
    
    alert.status = update.status
    if update.status == "sent":
        alert.sent_at = datetime.utcnow()
    
    db.commit()
    
    return {"success": True, "alert_id": alert_id, "new_status": update.status}


@router.delete("/{alert_id}")
def delete_alert(alert_id: int, db: Session = Depends(get_db)):
    """Delete an alert."""
    alert = db.query(ProactiveAlert).filter(ProactiveAlert.id == alert_id).first()
    if not alert:
        raise HTTPException(status_code=404, detail="Alert not found")
    
    db.delete(alert)
    db.commit()
    
    return {"success": True, "message": f"Alert {alert_id} deleted"}
